version: '3.9'
services:
  ingest-rf2:
    build: ./ingest
    depends_on:
      - snowstorm
    volumes:
      - ${PATH_TO_RF2_FILES}:/releases:ro
    restart: on-failure
    environment:
      - release=${release}
      - rf2_filename=${rf2_filename}

  elasticsearch:
    image: elasticsearch:7.17.4
    environment:
      - node.name=snowstorm
      - cluster.name=snowstorm-cluster
      - cluster.initial_master_nodes=snowstorm
      - "ES_JAVA_OPTS=-Xms8g -Xmx8g"
    volumes:
      - ${PATH_TO_ELASTIC_DB_STORAGE_LOCATION}:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://elasticsearch:9200"]
      interval: 1s
      timeout: 1s
      retries: 60
    expose:
      - "9200"

  snowstorm:
    image: snomedinternational/snowstorm:7.9.3
    restart: always
    depends_on:
      elasticsearch:
        condition: service_healthy
    entrypoint: java -Xms24g -Xmx24g -jar snowstorm.jar --elasticsearch.urls=http://elasticsearch:9200
    # entrypoint: java -Xms24g -Xmx24g -jar snowstorm.jar --elasticsearch.urls=http://elasticsearch:9200 --snowstorm.rest-api.readonly=true
    # entrypoint: java -Xms24g -Xmx24g -jar snowstorm.jar --elasticsearch.urls=http://elasticsearch:9200 --codesystem.all.latest-version.allow-future=true --codesystem.all.latest-version.allow-internal-release=true
    # entrypoint: java -Xms24g -Xmx24g -jar snowstorm.jar --elasticsearch.urls=http://elasticsearch:9200 #--delete-indices --import="/data/SnomedCT_InternationalRF2_PRODUCTION_20220228T120000Z.zip"
    ports:
      - 8080:8080
    expose:
      - "8080"

  snomedct-browser:
    image: snomedinternational/snomedct-browser:latest
    depends_on:
      - snowstorm
    environment:
      - API_HOST=http://snowstorm:8080/
    ports:
      - 80:80
    restart: always

networks:
  elastic:
